name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "2.8.1"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]
        flutter-channel: [stable]
#        flutter-channel: [stable, beta, dev]

    steps:
    - name: Git config long path
      run: git config --global core.longpaths true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: ${{ matrix.flutter-channel }}

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk
#
#    - name: Build iOS App
#      run: flutter build ios

    - name: Test App
      run: flutter test
